name: dev deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Version
        id: generate_version
        run: |
          # Set the current date and the first day of the month
          current_date=$(date +%Y-%m-%d)

          # Get the number of runs this month using GitHub API
          runs_this_month=$(curl -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs?event=push&status=completed&per_page=1&created=>$current_date"\
            | jq '.total_count')
          
          echo $runs_this_month
      
          # Set the output variable
          echo "runs_this_month=$runs_this_month" >> "$GITHUB_OUTPUT"
      - name: Deploy to dev
        run: |
          echo "Deploying to dev"
          echo "Runs this month: ${{ steps.generate_version.outputs.runs_this_month }}"
